MONGO_URI = "mongodb://localhost:27017"
DB_NAME = "mydatabase"
COLLECTION_NAME = "mycollection"

#AWS credentials
AWS_ACCESS_KEY_ID = "AKIAV3E7NPDIOXR2BCDB"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_REGION = "us-west-2"